[theme]
base = "light"
primaryColor = "#3157E2"
backgroundColor = "#F4F7FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#17213A"
font = "sans serif"

[server]
maxUploadSize = 25
headless = true

[browser]
gatherUsageStats = false
